# Serbian (Latin script) version of sectores_data.py
# (slug, es_slug, list name, Fini attribute "Label|with article|for the sentence", h1, lead, cta, h2, pains[(t,d,fix,type)], flow[(t,x)], audit)
S=[]
S.append(dict(slug="agencije-za-nekretnine",es_slug="inmobiliarias",name="Agencije za nekretnine",fini="Agencija za nekretnine|agencija za nekretnine|agencije za nekretnine",
h1="Svaki neodgovoren upit je razgledanje koje se neće dogoditi.",
lead="Upiti stižu sa portala, telefonom, preko WhatsApp-a i sa sajta, u bilo koje doba. Vaš tim je na razgledanjima. A praćenje zavisi od toga da li će se neko setiti.",
cta="Razgovarajmo o Vašoj agenciji",h2="Šta najviše vremena<br>oduzima agenciji za nekretnine.",
pains=[("Upiti van radnog vremena ili usred razgledanja","Upiti sa portala stižu noću, vikendom ili dok agent pokazuje drugi stan. Dok neko konačno odgovori, zainteresovani se već obratio drugim agencijama.","Klijent odmah dobija odgovor sa podacima o nekretnini i terminima za razgledanje. Agent nastavlja razgovor sa punim kontekstom.","Primenjena VI"),
("Kontakti razbacani na sve strane","Idealista, Fotocasa, sajt, imejl, WhatsApp svakog agenta i telefon u kancelariji. Niko nema potpunu sliku, a neki kontakti se usput izgube.","Svi kontakti, odakle god da stignu, ulaze na jedno mesto (Vaš CRM ili onaj koji zajedno izaberemo), bez ručnog prepisivanja.","Povezivanje alata"),
("Praćenje koje zavisi od pamćenja","Ponovo pozvati posle razgledanja, javiti za sniženje cene, vratiti se onome ko je rekao „razmisliću“. Ako se niko ne seti, prilika se ohladi.","Svaki kontakt ima zakazan sledeći korak: automatski zadaci i podsetnici za agenta i poruke za praćenje za klijenta.","Automatizacija"),
("Raspored razgledanja","Usklađivanje termina sa kupcima, vlasnicima i agentima, potvrđivanje, podsećanje i pomeranje oduzimaju dobar deo dana.","Razgledanja se automatski potvrđuju i najavljuju svakoj strani, a izmene se vide u kalendaru agenta bez poziva tamo-amo.","Automatizacija"),
("Vlasnici koji pitaju kako napreduje prodaja","„Koliko je razgledanja imao moj stan?“ Odgovaranje svakom vlasniku pojedinačno je vreme koje se ne posvećuje prodaji.","Svaki vlasnik redovno dobija pregled razgledanja i upita za svoju nekretninu, sastavljen od onoga što tim već beleži.","Automatizacija"),
("Preuzimanje nekretnina i dokumentacija","Izvod iz katastra, energetski pasoš, fotografije, podaci o vlasniku… Prikupljanje svega i pisanje oglasa traju, a uvek nešto nedostaje.","Spisak dokumentacije sa upozorenjima o onome što nedostaje i prvi nacrt oglasa za nekretninu, napisan uz pomoć VI na osnovu agentovih beleški.","Primenjena VI")],
flow=[("22:14","Stiže upit sa Idealiste za trosoban stan."),("22:15","Zainteresovani dobija odgovor sa podacima o nekretnini i terminima za razgledanje."),("22:15","Kontakt se evidentira u CRM-u i dodeljuje agentu za taj deo grada."),("09:00","Agent počinje dan sa pripremljenim upitom, istorijom i sledećim korakom."),("12:30","Razgledanje je potvrđeno i sistem šalje podsetnik klijentu i agentu."),("19:00","Posle razgledanja agent ostavlja glasovnu belešku, a praćenje se zakazuje automatski.")],
audit="Za nedelju dana proveravamo kako upiti stižu i kako se obrađuju, kako je organizovan raspored razgledanja i gde se gubi praćenje."))

S.append(dict(slug="knjigovodstvene-agencije",es_slug="gestorias",name="Knjigovodstvene i konsultantske agencije",fini="Knjigovodstvena agencija|knjigovodstvena i konsultantska agencija|knjigovodstvene i konsultantske agencije",
h1="Manje vremena u jurnjavi za papirima. Više vremena za savetovanje.",
lead="Dobar deo dana odlazi na traženje dokumenata, požurivanje onoga što nedostaje, odgovaranje na ista pitanja i praćenje rokova. Posao koji zaista donosi vrednost, savetovanje, ostaje za kraj.",
cta="Razgovarajmo o Vašoj agenciji",h2="Šta najviše vremena<br>oduzima knjigovodstvenoj agenciji.",
pains=[("Traženje i požurivanje dokumentacije","Fakture za kvartal, obračuni zarada, izvodi… Svaki klijent ih šalje kada stigne i kako stigne, a požurivanje jednog po jednog oduzima veliki deo svakog kvartala.","Svaki klijent dobija zahtev za ono što nedostaje i automatske podsetnike dok ne stigne, a da niko ne mora da ga juri.","Automatizacija"),
("Dokumenti koji stižu svim kanalima","Imejl, WhatsApp, fotografije telefonom, papir. Zatim neko mora da ih preimenuje, razvrsta i arhivira u pravi dosije.","Dokumenti stižu na jedno mesto, razvrstavaju se po klijentu i vrsti i automatski arhiviraju u odgovarajuću fasciklu.","Primenjena VI"),
("Rokovi i dospeća","Kvartalne poreske prijave, završni računi, obnove… Praćenje svega uz tabele i pamćenje stalni je rizik.","Kalendar obaveza za svakog klijenta, sa obaveštenjima Vašem timu i klijentu onoliko unapred koliko odlučite.","Automatizacija"),
("Ista pitanja, iznova i iznova","„Šta Vam treba od mene?“, „Kada se predaje?“, „Da li ste dobili ono što sam poslao?“ Svaki odgovor prekida posao.","Na uobičajena pitanja odgovara se odmah, sa podacima svakog klijenta, a ono što zahteva procenu stiže do knjigovođe sa kontekstom.","Primenjena VI"),
("Podaci koji se unose dvaput","Ono što stigne na fakturi unosi se u knjigovodstveni program, a zatim ponovo negde drugde.","Podaci se izvlače iz dokumenata i prelaze u Vaš poslovni softver, bez dvostrukog unosa.","Povezivanje alata"),
("Prijem novih klijenata","Ugovor, ovlašćenja, početna dokumentacija, otvaranje u programima… Svaki novi klijent je mali ručni projekat.","Vođen proces prijema: klijent zna šta treba da dostavi, potpisuje ono što je potrebno i otvoren je u Vašim alatima.","Automatizacija")],
flow=[("Dan 1","Počinje kvartal i svaki klijent dobija spisak onoga što treba da pošalje."),("Dan 3","Klijent šalje fakture preko WhatsApp-a; razvrstavaju se i arhiviraju u njegov dosije."),("Dan 5","Ko još ništa nije poslao dobija podsetnik, a da ga niko ne piše."),("Dan 8","Podaci sa faktura prelaze u knjigovodstveni program bez kucanja."),("Dan 10","Knjigovođa na prvi pogled vidi koji su klijenti kompletni, a koji nisu."),("Dan 15","Dosije je kompletan: knjigovođa dobija obaveštenje da pregleda i preda.")],
audit="Za nedelju dana proveravamo kako primate i organizujete dokumentaciju, kako pratite rokove i koliko vremena odlazi na zadatke koji se ponavljaju kod svakog klijenta."))

S.append(dict(slug="automobilski-sektor",es_slug="automocion",name="Automobilski sektor",fini="Automobilski sektor|firma iz automobilskog sektora|firme iz automobilskog sektora",
h1="Kupac koji čeka je automobil prodat negde drugde.",
lead="Upiti stižu sa portala za vozila, sa sajta, telefonom i preko WhatsApp-a. Kupac istovremeno poredi više opcija, a prodaju obično dobija onaj ko prvi odgovori korisnom informacijom.",
cta="Razgovarajmo o Vašem poslu",h2="Šta najviše vremena<br>oduzima firmi iz automobilskog sektora.",
pains=[("Upiti sa portala bez brzog odgovora","Coches.net, Wallapop, Milanuncios, sajt… Kada je prodavac sa drugim kupcem, upiti čekaju satima.","Trenutni odgovor sa specifikacijom vozila, cenom i mogućnošću zakazivanja, a zainteresovani se dodeljuje slobodnom prodavcu.","Primenjena VI"),
("Probne vožnje i termini na koje niko ne dođe","Probne vožnje, procene, primopredaje. Ako niko ne potvrdi i ne podseti, termin propada.","Automatska potvrda i podsetnik, uz mogućnost promene termina bez poziva.","Automatizacija"),
("Vozila ručno oglašena na više mesta","Postavljanje, ažuriranje i uklanjanje svakog vozila na svakom portalu traje i dovodi do grešaka, kao što su prodati automobili koji su i dalje oglašeni.","Ponuda vozila se objavljuje i ažurira sa jednog mesta na svim portalima.","Povezivanje alata"),
("Neodlučni kupci bez praćenja","„Razmisliću“ je najčešći odgovor. Bez praćenja, taj kupac na kraju kupi negde drugde.","Zakazano praćenje: korisne poruke u pravom trenutku i obaveštenje prodavcu kada kupac ponovo pokaže interesovanje.","Automatizacija"),
("Dokumentacija za prodaju","Ugovor, prenos vlasništva, finansiranje, garancija… Prikupljanje i proveravanje svakog papira usporava isporuku.","Spisak dokumentacije za svaku prodaju sa upozorenjima o onome što nedostaje i nacrti pripremljeni sa podacima o prodaji.","Primenjena VI"),
("Servis i postprodaja","Termini za servis, podsetnici za tehnički pregled i održavanje, predračuni za popravke. Mnogo telefona i mnogo sveski.","Podsetnici za održavanje svakom kupcu, onlajn zakazivanje servisa i predračuni koji se šalju i prihvataju bez poziva.","Automatizacija")],
flow=[("21:40","Sa portala stiže upit za jedan SUV."),("21:41","Zainteresovani dobija specifikaciju, cenu i termine za razgledanje ili probnu vožnju."),("21:41","Kontakt se evidentira i dodeljuje dežurnom prodavcu."),("09:15","Prodavac počinje dan sa upitom i istorijom kupca."),("Dan ranije","Kupac i prodavac dobijaju podsetnik za probnu vožnju."),("Posle vožnje","Ako se kupac ne odluči, praćenje se zakazuje automatski.")],
audit="Za nedelju dana proveravamo kako stižu i kako se obrađuju Vaši potencijalni klijenti, kako se upravlja probnim vožnjama i terminima i gde se prodaje gube zbog nedostatka praćenja."))

S.append(dict(slug="gradnja-renoviranje",es_slug="construccion-reformas",name="Gradnja i renoviranje",fini="Renoviranje|firma za renoviranje|građevinske firme i firme za renoviranje",
h1="Ponuda koja se čeka nedelju dana obično stigne prekasno.",
lead="Zahtevi stižu nepotpuni, svaka ponuda se pravi od nule, a radovi se koordiniraju pozivima i porukama. U međuvremenu klijent nastavlja da traži cene od drugih.",
cta="Razgovarajmo o Vašoj firmi",h2="Šta najviše vremena<br>oduzima firmi za renoviranje.",
pains=[("Nepotpuni zahtevi","„Hoću da renoviram kupatilo, koliko bi to koštalo?“ Bez mera, fotografija i detalja, potrebno je nekoliko poziva pre nego što može da se napravi ponuda.","Svaki zahtev odmah dobija pitanja koja nedostaju (mere, fotografije, materijali) i do tima stiže već kompletan.","Automatizacija"),
("Ponude od nule","Svaka ponuda se sastavlja ručno, stavku po stavku, iako je polovina slična ranijim ponudama.","Nacrt ponude na osnovu zahteva i Vaših uobičajenih stavki, spreman da ga pregledate i pošaljete.","Primenjena VI"),
("Koordinacija na gradilištu","Ekipe, majstori, materijal i posete klijenta organizuju se telefonom i preko WhatsApp-a, i uvek nešto promakne.","Zajednički plan rada, sa automatskim obaveštenjima svakom majstoru i klijentu kada se nešto promeni.","Automatizacija"),
("Radni nalozi i praćenje radova","Fotografije, sati i napredak ostaju u telefonu svakog radnika, a klijent stalno pita kako napreduju radovi.","Radni nalozi sa telefona koji uredno stižu u kancelariju i redovan pregled za klijenta.","Povezivanje alata")],
flow=[("18:30","Sa sajta stiže zahtev za renoviranje kuhinje."),("18:31","Klijent dobija ključna pitanja i šalje fotografije i mere."),("Dan 1","Sa kompletnim informacijama priprema se nacrt ponude."),("Dan 2","Odgovorna osoba ga pregleda i šalje uz tlocrt i vizualizaciju pre i posle."),("Dan 5","Ako nema odgovora, šalje se automatska poruka za praćenje."),("Na gradilištu","Dnevni radni nalozi stižu u kancelariju, a klijent dobija nedeljni pregled.")],
audit="Za nedelju dana proveravamo kako stižu zahtevi, koliko traje izrada ponude i kako se koordiniraju i prate radovi.",
feature=dict(eyebrow="DODATNA VREDNOST ZA PRIDOBIJANJE KLIJENATA",h2="Neka klijent vidi svoje renoviranje<br>pre nego što potpiše.",
p="Ko traži tri ponude, na kraju poredi brojke. Ako iz Vaše vidi kako njegov dom izgleda danas i kako će izgledati posle renoviranja, prestaje da poredi samo cene i počinje da zamišlja sebe u njemu.",
items=["2D tlocrt sa postojećim rasporedom i predlogom.","3D vizualizacija pre i posle, sa materijalima i završnim obradama.","Sve u dosijeu sa vizuelnim identitetom Vaše firme, uz ponudu."],
ba=True)))

S.append(dict(slug="upravnici-zgrada",es_slug="administradores-fincas",name="Upravnici zgrada",fini="Upravljanje zgradama|firma za profesionalno upravljanje zgradama|profesionalne upravnike zgrada",
h1="Svaka zgrada, telefon koji ne prestaje da zvoni.",
lead="Kvarovi, pitanja stanara, skupštine, vanredni troškovi i mesečne uplate. Veliki deo dana odlazi na odgovaranje, prosleđivanje i podsećanje, a vrlo malo na upravljanje.",
cta="Razgovarajmo o Vašoj firmi",h2="Šta najviše vremena<br>oduzima upravniku zgrada.",
pains=[("Prijave kvarova sa svih strana","Pozivi, imejlovi i poruke više stanara zbog istog kvara, a zatim dogovor sa majstorom i obaveštavanje svih.","Svaka prijava se evidentira jednom i dodeljuje izvođaču, a stanari dobijaju obaveštenja o statusu bez pozivanja.","Automatizacija"),
("Skupštine i pozivi za sednice","Priprema poziva, slanje, prikupljanje punomoćja i pisanje zapisnika oduzimaju sate za svaku stambenu zajednicu.","Pozivi koji se automatski šalju i prate i prvi nacrt zapisnika na osnovu beleški sa sednice.","Primenjena VI"),
("Uplate i vraćeni nalozi","Otkrivanje neplaćenih obaveza, obaveštavanje stanara i praćenje, zajednicu po zajednicu.","Automatska obaveštenja o vraćenim nalozima i zakazano praćenje dok se dug ne izmiri.","Automatizacija"),
("Obaveštenja stanarima","Isključenja vode, radovi, vanredni troškovi. Obaveštavanje svake zajednice pravim kanalom posao je za sebe.","Obaveštenja pripremljena jednom i poslata pravoj stambenoj zajednici, kanalom koji svaki stanar koristi.","Povezivanje alata")],
flow=[("08:10","Stanar preko WhatsApp-a prijavljuje curenje u garaži."),("08:11","Prijava se evidentira i stanar dobija potvrdu."),("08:15","Stalni vodoinstalater dobija obaveštenje sa adresom i fotografijama."),("08:20","Ostali stanari dobijaju obaveštenje: problem se rešava, nema potrebe da zovu."),("12:00","Vodoinstalater zatvara radni nalog i zajednica je obaveštena."),("Kraj meseca","Upravnik ima istoriju prijava za svaku zgradu, a da je nije ručno sastavljao.")],
audit="Za nedelju dana proveravamo kako prijave stižu i kako se rešavaju, kako pripremate skupštine i obaveštenja i koliko vremena odlazi na zadatke koji se ponavljaju u svakoj stambenoj zajednici."))

S.append(dict(slug="klinike",es_slug="clinicas",name="Klinike",fini="Klinika|klinika|klinike",
h1="Svaki prazan termin u rasporedu je vreme koje se ne vraća.",
lead="Zahtevi za termine van radnog vremena, podsetnici koji se šalju ručno, pacijenti koji ne dođu i otkazivanja u poslednjem trenutku. Recepcija se na kraju pretvori u pozivni centar.",
cta="Razgovarajmo o Vašoj klinici",h2="Šta najviše vremena<br>oduzima klinici.",
pains=[("Zakazivanje van radnog vremena","Mnogi pacijenti traže termin noću ili vikendom, kada niko ne može da im odgovori.","Trenutni odgovor sa slobodnim terminima i termin rezervisan direktno u Vašem kalendaru.","Automatizacija"),
("Pacijenti koji ne dođu","Bez podsetnika deo termina propada, a to mesto više ne može da se popuni.","Automatski podsetnici sa mogućnošću da se termin potvrdi ili promeni jednim klikom.","Automatizacija"),
("Otkazivanja u poslednjem trenutku","Kada neko otkaže, pozivanje jednog po jednog sa liste čekanja retko uspe na vreme.","Oslobođeni termin se automatski nudi pacijentima sa liste čekanja.","Automatizacija"),
("Ista pitanja na recepciji","Cene, priprema pre pregleda, radno vreme, kako doći… Uvek ista.","Na uobičajena pitanja odgovara se odmah, a recepcija se posvećuje onima koji su u klinici.","Primenjena VI")],
flow=[("23:05","Pacijent zakazuje termin preko sajta."),("23:05","Dobija slobodne termine i rezerviše onaj koji mu najviše odgovara."),("Dan ranije","Stiže mu podsetnik i potvrđuje jednim klikom."),("09:30","Drugi pacijent otkazuje i termin se nudi listi čekanja."),("09:40","Pacijent sa liste čekanja ga prihvata i raspored je popunjen.")],
audit="Za nedelju dana proveravamo kako se termini zakazuju, potvrđuju i gube i koji deo posla recepcije može da se oslobodi. Uvek uz najveću brigu o podacima pacijenata."))

S.append(dict(slug="kratkorocni-najam",es_slug="alquiler-vacacional",name="Kratkoročni najam",fini="Kratkoročni najam|firma za upravljanje kratkoročnim najmom|kratkoročni najam",
h1="Gosti pišu u bilo koje doba. Samo jedna osoba da odgovori.",
lead="Pitanja pre rezervacije, uputstva za dolazak, problemi tokom boravka, čišćenje između gostiju i obavezna prijava gostiju. Sve se ponavlja sa svakom rezervacijom.",
cta="Razgovarajmo o Vašim smeštajima",h2="Šta najviše vremena<br>oduzima upravniku kratkoročnog najma.",
pains=[("Poruke u svako doba","„U koliko sati mogu da se prijavim?“, „Gde da parkiram?“, „Koja je šifra za wifi?“ Ista pitanja, na svakoj platformi i u bilo koje doba.","Trenutni odgovori sa podacima o svakom smeštaju, a ono za šta je potreban čovek stiže do upravnika sa kontekstom.","Primenjena VI"),
("Dolasci i odlasci","Slanje uputstava, pristupnih kodova i kućnog reda svakom gostu u pravom trenutku.","Automatske poruke pre dolaska, tokom boravka i pri odlasku, sa podacima o svakoj rezervaciji.","Automatizacija"),
("Koordinacija čišćenja","Obaveštavanje ekipe za čišćenje o svakom odlasku, rešavanje izmena u poslednjem trenutku i proveravanje da li je sve spremno.","Svaka rezervacija pokreće svoje čišćenje: ekipa dobija obaveštenje i potvrđuje kada je smeštaj spreman.","Automatizacija"),
("Prijava gostiju i više platformi","Prepisivanje podataka gostiju za obaveznu prijavu i usklađivanje rezervacija između platformi zamorno je i podložno greškama.","Podaci za svaku rezervaciju prikupljaju se samo jednom i pripremaju za prijavu, a rezervacije sa svih platformi objedinjuju se u jednom kalendaru.","Povezivanje alata")],
flow=[("Rezervacija","Sa platforme stiže rezervacija i dodaje se u zajednički kalendar."),("Dan ranije","Gost dobija uputstva za dolazak i link za unos svojih podataka."),("15:00","Gost pita za parking i odmah dobija odgovor."),("Odlazak","Ekipa za čišćenje dobija obaveštenje i potvrđuje kada završi."),("Sutradan","Gost dobija zahvalnicu i poziv da ostavi recenziju.")],
audit="Za nedelju dana proveravamo kako upravljate komunikacijom sa gostima, dolascima, čišćenjem i prijavom gostiju i koji deo se ponavlja sa svakom rezervacijom."))

S.append(dict(slug="instalateri-odrzavanje",es_slug="instaladores-mantenimiento",name="Instalateri i održavanje",fini="Instalacije i održavanje|firma za instalacije i održavanje|instalatere i firme za održavanje",
h1="Tehničar na terenu. Kancelarija na telefonu. Radni nalozi u svesci.",
lead="Prijave kvarova, predračuni, termini, radni nalozi i periodični pregledi. Kada sve ide preko telefona, uvek nešto ostane neurađeno.",
cta="Razgovarajmo o Vašoj firmi",h2="Šta najviše vremena<br>oduzima firmi za instalacije.",
pains=[("Prijave koje stižu svim kanalima","Pozivi, WhatsApp poruke i imejlovi o kvarovima, i svaki put treba pitati isto: adresa, uređaj, simptomi, hitnost.","Svaka prijava se evidentira sa svim potrebnim informacijama i dodeljuje odgovarajućem tehničaru.","Automatizacija"),
("Termini i rute","Uklapanje intervencija, potvrđivanje sa klijentom i javljanje o kašnjenjima oduzimaju dobar deo dana u kancelariji.","Termini se automatski potvrđuju i najavljuju, a klijent dobija obaveštenje kada je tehničar na putu.","Automatizacija"),
("Radni nalozi na papiru","Sati, materijal i potpisi na papiru ili u telefonu tehničara, koje zatim neko mora da prepiše za fakturisanje.","Radni nalozi sa telefona koji stižu u kancelariju spremni za fakturisanje, bez ponovnog kucanja.","Povezivanje alata"),
("Periodični pregledi i održavanje","Obavezni pregledi, ugovori o održavanju, garancije… Ako ih se niko ne seti, gube se klijenti i posao.","Svaki klijent na vreme dobija podsetnik za svoj pregled, a termin se zakazuje bez poziva.","Automatizacija")],
flow=[("08:05","Klijent preko WhatsApp-a javlja da mu klima-uređaj ne hladi."),("08:06","Dobija ključna pitanja i šalje fotografiju uređaja."),("08:10","Prijava se dodeljuje tehničaru za to područje sa svim informacijama."),("11:40","Klijent dobija obaveštenje: tehničar stiže za dvadeset minuta."),("12:30","Tehničar zatvara radni nalog u telefonu i klijent potpisuje."),("12:31","Radni nalog stiže u kancelariju spreman za fakturisanje.")],
audit="Za nedelju dana proveravamo kako stižu prijave, kako se organizuju termini i rute i koliko vremena odlazi na prepisivanje radnih naloga i pamćenje pregleda."))

S.append(dict(slug="obrazovni-centri",es_slug="academias",name="Obrazovni centri i obuke",fini="Obrazovni centar|obrazovni centar|obrazovne centre i kurseve",
h1="Svakog septembra ista pitanja. I sva odjednom.",
lead="Zahtevi za informacije, upisi, mesečne uplate i obaveštenja polaznicima i porodicama. U vrhuncu upisa, odgovor na vreme pravi razliku između popunjenih i nepopunjenih grupa.",
cta="Razgovarajmo o Vašem centru",h2="Šta najviše vremena<br>oduzima obrazovnom centru.",
pains=[("Upiti u sezoni","Raspored, cene, nivoi, slobodna mesta. U septembru i januaru mnogo upita stiže odjednom, a na neke se ne odgovori na vreme.","Trenutni odgovor sa podacima o svakom kursu i mogućnošću rezervacije mesta ili probnog časa.","Primenjena VI"),
("Ručni upisi","Papirni obrasci, podaci prepisani u tabelu, dokumentacija koja nedostaje.","Onlajn upis sa podacima koji su Vam potrebni, koji direktno prelaze u Vaše alate.","Povezivanje alata"),
("Uplate i direktna zaduženja","Praćenje mesečnih uplata i vraćenih naloga i podsećanje onih koji nisu platili, polaznika po polaznika.","Automatska obaveštenja o neizmirenim uplatama i praćenje do naplate.","Automatizacija"),
("Komunikacija sa polaznicima i porodicama","Promene rasporeda, izostanci, obaveštenja o ispitima. Sve preko WhatsApp grupa koje izmaknu kontroli.","Obaveštenja poslata pravoj grupi ili polazniku, uz evidenciju onoga što je saopšteno.","Automatizacija")],
flow=[("22:00","Porodica se raspituje o časovima engleskog za sina."),("22:00","Dobija raspored, nivoe i mogućnost da rezerviše probni čas."),("Posle probnog časa","Stiže im link za završetak upisa."),("Pri upisu","Podaci prelaze u Vaš spisak polaznika i sistem naplate."),("Svakog meseca","Uplata se obrađuje automatski, a obaveštenje stiže samo ako nešto ne uspe.")],
audit="Za nedelju dana proveravamo kako odgovarate na upite, kako upravljate upisima i uplatama i kako komunicirate sa polaznicima i porodicama."))

S.append(dict(slug="brokeri-osiguranja",es_slug="corredurias-seguros",name="Brokeri osiguranja",fini="Broker osiguranja|brokersko društvo u osiguranju|brokere osiguranja",
h1="Svaka zaboravljena obnova je klijent koji odlazi drugom brokeru.",
lead="Istek polisa, štete, dokumentacija i poređenja ponuda. Praćenje svake polise previše zavisi od kalendara i pamćenja svake osobe.",
cta="Razgovarajmo o Vašem društvu",h2="Šta najviše vremena<br>oduzima brokeru osiguranja.",
pains=[("Obnove i istek polisa","Praćenje koja polisa ističe, obaveštavanje na vreme i priprema alternativa, klijenta po klijenta.","Automatska obaveštenja o isteku klijentu i Vašem timu onoliko unapred koliko odlučite i praćenje do zaključenja obnove.","Automatizacija"),
("Obrada šteta","Klijent zove zabrinut; treba prikupiti podatke, fotografije i izveštaje, proslediti ih osiguravaču i obaveštavati klijenta o svakom koraku.","Vođena prijava štete, sa dokumentacijom koja se prikuplja samo jednom i obaveštenjima klijentu pri svakoj promeni statusa.","Automatizacija"),
("Dokumentacija klijenata","Lične karte, vozačke dozvole, ugovori o kupoprodaji, saobraćajne dozvole… Traženje, prijem i arhiviranje na pravo mesto oduzimaju vreme.","Automatsko traženje onoga što nedostaje i uredno arhiviranje po klijentu i po polisi.","Primenjena VI"),
("Podaci rasuti između programa i osiguravača","Podaci o svakom klijentu nalaze se u poslovnom softveru, u imejlu i na sajtovima osiguravača.","Podaci se povezuju tako da Vaš tim ima potpun profil svakog klijenta na jednom mestu.","Povezivanje alata")],
flow=[("45 dana ranije","Sistem otkriva da polisa osiguranja stana ističe za mesec i po."),("40 dana ranije","Klijent dobija obaveštenje, a broker zadatak da pregleda alternative."),("30 dana ranije","Ako klijent nije odgovorio, šalje se podsetnik."),("20 dana ranije","Broker zove sa već pripremljenim predlogom."),("Obnovljeno","Polisa je obnovljena, a klijent je na vreme dobio pažnju.")],
audit="Za nedelju dana proveravamo kako pratite istek polisa i obnove, kako obrađujete štete i gde se rasipaju podaci o svakom klijentu."))

S.append(dict(slug="teretane-studiji",es_slug="gimnasios-estudios",name="Teretane i fitnes studiji",fini="Teretana ili studio|teretana ili fitnes studio|teretane i fitnes studije",
h1="Član koji prestane da dolazi je ispis koji još možete da sprečite.",
lead="Upisi, ispisi, članarine, rezervacije časova, liste čekanja i uobičajena pitanja. Ako sve ide preko recepcije, niko nema vremena da primeti ko prestaje da dolazi.",
cta="Razgovarajmo o Vašem centru",h2="Šta najviše vremena<br>oduzima teretani ili studiju.",
pains=[("Ispisi koje niko ne vidi unapred","Član prestane da dolazi i, kada se ispiše, već je kasno.","Obaveštenje timu kada član neko vreme ne dolazi i poruka za ponovno uspostavljanje kontakta.","Automatizacija"),
("Upiti novih klijenata","Cene, raspored, probni časovi. Ako se ne odgovori brzo, zainteresovani se upiše negde drugde.","Trenutni odgovor sa informacijama i mogućnošću rezervacije probnog časa.","Primenjena VI"),
("Rezervacije i liste čekanja","Popunjeni časovi, otkazivanja u poslednjem trenutku i mesta koja ostanu prazna.","Onlajn rezervacije sa automatskom listom čekanja: ako neko otkaže, mesto se nudi sledećem.","Automatizacija"),
("Članarine i vraćeni nalozi","Praćenje uplata, naplata vraćenih naloga i promene tarifa, člana po člana.","Automatska obaveštenja o neizmirenim uplatama i praćenje dok se ne reše.","Automatizacija")],
flow=[("21:30","Neko se preko Instagrama raspituje o časovima pilatesa."),("21:30","Dobija raspored, cene i link za rezervaciju probnog časa."),("Posle probnog časa","Dobija ponudu za učlanjenje."),("Svake nedelje","Rezerviše časove preko telefona; ako otkaže, mesto prelazi na listu čekanja."),("Ne dolazi","Ako nekoliko nedelja ne dolazi, tim dobija obaveštenje da ponovo uspostavi kontakt.")],
audit="Za nedelju dana proveravamo kako odgovarate zainteresovanima, kako upravljate rezervacijama, članarinama i ispisima i koji deo posla recepcije može da se oslobodi."))

S.append(dict(slug="distributeri",es_slug="distribuidores",name="Distributeri i veletrgovci",fini="Distribucija|distributivna firma|distributere i veletrgovce",
h1="Svaka ručno ukucana porudžbina je greška koja čeka da se dogodi.",
lead="Porudžbine stižu preko WhatsApp-a, imejlom i telefonom, svaki klijent na svoj način. Neko ih ručno prepisuje, proverava zalihe na drugom mestu i priprema otpremnice jednu po jednu. Greške skupo koštaju, a vreme odlazi na poslove koji ne donose prodaju.",
cta="Razgovarajmo o Vašoj firmi",h2="Šta najviše vremena<br>oduzima distributeru.",
pains=[("Porudžbine svim kanalima","WhatsApp poruke, imejlovi, pozivi, pa čak i fotografije iz sveske. Neko mora da ih protumači i ukuca.","Porudžbine se čitaju, tumače i unose u Vaš sistem, spremne za pregled i potvrdu.","Primenjena VI"),
("Upiti o zalihama i cenama","„Imate li još?“, „Koliko košta?“ Svako pitanje znači proveru u drugom programu i ručni odgovor.","Trenutni odgovor sa stanjem zaliha i uslovima za svakog klijenta, povezan sa Vašim sistemom.","Povezivanje alata"),
("Otpremnice, fakture i potvrde","Priprema dokumenata i potvrđivanje svake porudžbine klijentu ponavljaju se i ostavljaju prostor za greške.","Potvrde, otpremnice i fakture generisane iz porudžbine, bez ponovnog kucanja.","Automatizacija"),
("Neizmirena potraživanja","Proveravanje dospeća i opominjanje za neplaćene fakture, klijenta po klijenta.","Automatska obaveštenja o dospeću i praćenje neplaćenih faktura do naplate.","Automatizacija")],
flow=[("07:50","Klijent preko WhatsApp-a šalje porudžbinu sa spiskom proizvoda."),("07:51","Porudžbina se tumači i unosi u sistem, u statusu čekanja na potvrdu."),("08:30","Tim je pregleda i potvrđuje jednim klikom; klijent dobija potvrdu."),("10:00","Otpremnica se generiše automatski i porudžbina izlazi iz magacina."),("Pri isporuci","Faktura se izdaje, a naplata se zakazuje.")],
audit="Za nedelju dana proveravamo kako Vam porudžbine stižu i kako se obrađuju, kako se proveravaju zalihe i cene i koliko ručnog rada ima između porudžbine i naplate."))
